baseURL = "https://portfolio-fi32k.ondigitalocean.app/"
languageCode = "en-us"
title = "Furl"
theme = "cactus"
copyright = "Bastian Zakolski" # cactus will use title if copyright is not set
disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"


# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 10

#[[menu.main]]
#name = "Games"
#url = "/categories/games"
#weight = 15

#[[menu.main]]
#name = "CG"
#url = "/categories/cg/"
#weight = 20

#[[menu.main]]
#name = "Music"
#url = "/categories/music/"
#weight = 25

#[[menu.main]]
#name = "Illustration"
#url = "/categories/illustration/"
#weight = 30

#[[menu.main]]
#name = "All"
#url = "/posts"
#weight = 35

#[[menu.main]]
#name = "Tags"
#url = "/tags"
#weight = 40



[[menu.main]]
name = "About"
url = "/about"
weight = 50

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
logo = "images/profile01black.gif"
#gravatar = true
postsTitle = "Latest"

  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "Welcome. I'm currently moving to a static webpage."
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/bzxo" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "instagram"
    link = "https://instagram.com/ffuurrll"
  [[params.social]]
    name = "github"
    link = "https://github.com/bzxo"
  #[[params.social]]
  #  name = "linkedin"
  #  link = "https://www.linkedin.com/company/github/"
  [[params.social]]
    name = "email"
    link = "bastian@zakol.ski"  # no need for "mailto:" in the head
